# .github/workflows/main.yml
name: Main

on:
  schedule:
    - cron: '0 0 * * *' # Midnight
  workflow_dispatch:

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Mirror Directory Structure
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.DRIVE_CREDENTIALS }}
          filename: journaux/*/*
          folderId: ${{ secrets.folderId }}
          overwrite: "true"
          mirrorDirectoryStructure: "true"
          